- name: conditions
  hosts: local
  connection: local

  vars:
    number: 5

  tasks:
  - name: check if a number is less than 10
    ansible.builtin.debug:
      msg: "Given num : {{number}} is < 10"
    when: number < 10