- name: installing packages
  hosts: local
  connection: local
  become: yes

  tasks:
    - name: Installing packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.state }}"

      loop:
        - {name: "nginx", state: "latest"}
        - {name: "mysql", state: "latest"}
        - {name: "zip", state: "latest"} #latest installs latest version, absent removes the app
